### ISSUE TITLE
Add client stories

### ISSUE THREAD

**Issue by clairehubel** [theunitedeffort/theunitedeffort.org#135]
We now have some little snippets of stories of various clients, with a short video, a few photos, and a link to an Etsy store the one of our clients set up. It would be great if we could add a way to feature these.

Want to chat tomorrow about how to structure this, @philhawksworth ? Ideally I would be able to add content myself, just have a few questions about where to put it all :)

**Comment by trevorshannon** [comment]
The home page is currently a bit generic with the mission statement, etc.  Client stories could snazz it up a bit

**Comment by clairehubel** [comment]
I agree, especially since our clients are such a wonderful group of colorful and diverse characters ❤️ Featuring some of them would be a good reminder to us of why we are actually doing all this work :)

I'm wondering if the homepage ultimately should have some kind of rolling news story, that is about something important that comes up. For instance, Medi-Cal was not formerly offered to undocumented folks, other than in emergencies, but since May 1st all undocumented people over the age of 50 can get full scope Medi-cal. This is huge for our clients. I could imagine having a catchy headline, some photos, and the first paragraph of an article about this, with a 'click here to continue reading about this' at the end, taking the reader to a more full article, with steps on how to apply, etc.

I have also considered doing visits to places that are good resources for people to learn about, such as Downtonw Streets Team. I'd love to go there, learn about the program, take some photos, and do a write up. This would give them some publicity, make valuable connections for us, as well as give us some interesting content.

We could even feature our instagram feed as the main item on the home page......just a few ideas to think about. Ultimately it would be good if this were a good place for curated resources and news that is helpful.

My main issue as always is too many ideas and too little time.  :)  But now we have a solid foundation these things become an option.

**Comment by clairehubel** [comment]
Brainstorm of clients to feature:
Fred (video)
Bruce
Jack (video)
Sherice (Etsy store)
Johnny (just earned real estate license)
Jeremy (poetry)
Terry (housing)
Ike (housing)
John (housing and 83rd birthday celebration)
Keith (helper at HC during pandemic)
Mike (ongoing support in post-housing period)
Chris (sobriety and employment)

**Comment by trevorshannon** [comment]
The initial set of client stories is live, with the work completed in #520
