### ISSUE TITLE
Housing results buttons are not side-by-side in Safari

### ISSUE THREAD

**Issue by trevorshannon** [theunitedeffort/theunitedeffort.org#159]
There are some buttons which appear above the results when a housing search has more than zero results.  These buttons should be all the way on the right side of the viewport and in line with each other.  However, they render stacked (one on top of the other) in Safari.

The **Print summary of results** and **Show results as a checklist** buttons should be side-by-side.

<img width="1126" alt="Screen Shot 2022-07-07 at 3 29 28 PM" src="https://user-images.githubusercontent.com/4656936/177882159-94e6cb46-7876-4118-adef-c77d139b8858.png">

**Comment by trevorshannon** [comment]
The above screenshot is from my own computer running Safari 14.0.3 on mac OS 10.15.7

**Comment by rajivrajiv** [comment]
Could you please assign this to me? 
Thanks,

**Comment by rajivrajiv** [comment]
Please unassign thsi.
Thanks,

**Comment by trevorshannon** [comment]
Wonderful, thank you!  Let me know if you need any help getting your development environment set up.

I just confirmed this is still an issue on macOS 13.2 and Safari version 16.3 (18614.4.6.1.5)

**Comment by Daniel-olaO** [comment]
Okay, thanks

**Comment by Daniel-olaO** [comment]
Hi, I keep getting errors when starting app and I can't get safari on my windows

**Comment by trevorshannon** [comment]
If you show me the errors, I can help you work through them.  I'm not, however, able to get you Safari.  It's technically possible to use a browser testing service if you want to go that route.  I can also un-assign this if you prefer.

**Comment by Daniel-olaO** [comment]
you can go ahead and unassign it
