### ISSUE TITLE
Display all contact information

### ISSUE THREAD

**Issue by trevorshannon** [theunitedeffort/theunitedeffort.org#272]
Properties have `SECOND_EMAIL` and `SECOND_PHONE` fields now, and that data should be displayed on the property details pages.

There is also an existing `SECOND_ADDRESS` field that could be displayed.

**Comment by gangaramani-nikhil** [comment]
Hi @trevorshannon,

I can work on this issue

**Comment by trevorshannon** [comment]
Great!  There is some precedent for showing multiple entries [here](https://github.com/theunitedeffort/theunitedeffort.org/blob/dfa9c708d61249de68a57862a0f4fce5219c0f55/src/site/_includes/apartment-meta-item.liquid#L11)

The `SECOND_*` data should only be shown if it exists

**Comment by trevorshannon** [comment]
@gangaramani-nikhil I'm hoping to solve this issue with the next website release (likely in a month or so).  Shall I assign this issue to myself, or are you still interested in taking it on?
