### ISSUE TITLE
Map Enter key to either Next or Finish button

### ISSUE THREAD

**Issue by trevorshannon** [theunitedeffort/theunitedeffort.org#276]
When filling out the eligibility form, we should consider mapping the Enter key to the Next/Finish button (depending on whether the user is on the last page or not).

Pressing Enter currently only advances the form page if the button is in focus.

**Comment by gangaramani-nikhil** [comment]
I can work on this issue

**Comment by gangaramani-nikhil** [comment]
I have added another commit in this #331 pull request which solves this issue

**Comment by gangaramani-nikhil** [comment]
https://user-images.githubusercontent.com/52930019/227943488-e3057de7-157f-481c-9550-67f5aa753d55.mov

**Comment by gangaramani-nikhil** [comment]
I am click on enter and its click on the next button
