### ISSUE TITLE
Add commas to income totals

### ISSUE THREAD

**Issue by trevorshannon** [theunitedeffort/theunitedeffort.org#277]
The total income for a given income type is displayed on each income details page.  This value is formatted as a number with a preceding **$**

Including commas appropriately would make the value easier to read. e.g. $3,125 vs $3125

**Comment by gangaramani-nikhil** [comment]
I can work on this issue

**Comment by trevorshannon** [comment]
That would be great!  Let me know if you need any support.  Here's a [starting point](https://github.com/theunitedeffort/theunitedeffort.org/blob/c3e9aab6b24370addab582a3696490ca694f8686/src/site/static/eligibility.liquid#L1044).

**Comment by gangaramani-nikhil** [comment]
I have asked for readonly access to the AirTable base.

**Comment by trevorshannon** [comment]
@clairehubel Can you ensure Nikhil gets read-only access to the Housing Database table?

**Comment by gangaramani-nikhil** [comment]
I have the access now Thanks

**Comment by gangaramani-nikhil** [comment]
I have fixed this issue
![image](https://user-images.githubusercontent.com/52930019/227770181-6c956e19-0d13-4d83-b5b5-4044e9451bec.png)
