### ISSUE TITLE
Add translation option 

### ISSUE THREAD

**Issue by trevorshannon** [theunitedeffort/theunitedeffort.org#29]
Similar to [this](https://www.findhelp.org) website, it would be great if the UEO website could be displayed in languages other than English.  @clairehubel can you update this issue with the priority list of languages?

**Comment by trevorshannon** [comment]
The very easy-to-use Google website translator widget is no longer supported :(

**Comment by clairehubel** [comment]
Damn! That's too bad. Do you have other ideas for how to accomplish this? Is there a way to see how it is done on the website referenced above? I wouldn't say its a requirement for the launch, but definitely on the list of important things to have, if poss. Spanish would be the most important, followed by Vietnamese. We could add Chinese as well, but this will be more important with the resources database, and not so critical for the housing db. (Not many unhoused Chinese folks)

**Comment by trevorshannon** [comment]
Google does still have a Translate API we may be able to use.  I'll do some more research.
