### ISSUE TITLE
Add checkbox for users to explicitly say they have no assets.

### ISSUE THREAD

**Issue by trevorshannon** [theunitedeffort/theunitedeffort.org#397]
Similar to the Income sub-section, we should have a checkbox in the Assets sub-section that users can check if they have zero assets.  When that box is checked, the interactive elements to add assets should be deactivated, and any assets already added should be removed or zeroed out.

**Comment by DairyProducts** [comment]
Assets do not seem to be assigned unique IDs for each one added. How should this be done?

![image](https://github.com/theunitedeffort/theunitedeffort.org/assets/66636627/3d0f8431-cc08-44ea-acf1-33ce3b7ada54)

**Comment by trevorshannon** [comment]
The individual Value fields do have unique IDs (e.g. `income-assets-member1-0`).  The container `<div>`s do not.  You can use query selectors to get those if you need.   Here are some examples, depending on which container element you need:

```js
document.querySelectorAll('#page-income-assets .dynamic_field_list');
document.querySelectorAll('#page-income-assets fieldset');
document.querySelectorAll('#page-income-assets .dynamic_field_list_wrapper');
```

Here's one idea to achieve the goal:

When the user clicks on some new checkbox to say they have no assets, handle that event with a function that removes all items from all assets lists (there may be more than one list since each household member can have assets) and disables the "Enter an asset for this person" buttons.  There is a function called `removeDynamicFieldListItem` that could be helpful, and I think `resetDynamicFieldLists` might be even more helpful.  I'm pretty sure that just removing the entries should be enough; no need to explicitly zero each one out or anything.

I feel like the new checkbox should be near the bottom so that it's closer to the Next button, but I'm open to other ideas.

**Comment by trevorshannon** [comment]
It would be nice to have this functionality in place when we release this tool to the public at the end of June, but not strictly necessary.  @DairyProducts how are you feeling about this issue?

**Comment by DairyProducts** [comment]
My apologies for not replying or taking action sooner. I've been out of the country since early June and unable to access my computer. I'll be back next week; I will work on this as soon as possible.

**Comment by trevorshannon** [comment]
No problem at all!  I'll move this to the next release milestone and you can work on it whenever you have time.  Enjoy your time away from home.

**Comment by DairyProducts** [comment]
I'm not sure how the schema for setting up listeners for elements works. In the latest commit to the branch I've attempted to set up a listener on the new checkbox but it appears to not be working (tested with console.log function in onNoAssetCheck).

**Comment by trevorshannon** [comment]
It looks like the click listener is working to me, nice job!  I checked out your `eligibility/no-asset-checkbox` [branch](https://github.com/theunitedeffort/theunitedeffort.org/compare/main...eligibility/no-asset-checkbox) and I see `pass` in the console when I click your new checkbox in Chrome 114.

One thing that _may_ cause an issue (depends on the browser): the `id` of your `<ul>` is `hh-member-types` which was already used in the document, and `id`s need to be unique.

I also noticed your feature branch is pretty far behind `main`.  It could be that `main` has advanced since you made that branch, or it could be that you had not done a `git pull` before creating the local branch off `main`.  When you merge `main` into `eligibility/no-asset-checkbox` (which I suggest you do sooner rather than later in order to get your feature branch up to date with `main`) there will be some merge conflicts, which are always a pain.  Let me know if you need any help [resolving](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line) those.

You can merge `main` in to your branch with the GitHub Desktop client or with:
```
git checkout main
git pull
git checkout eligibility/no-asset-checkbox
git merge main
```

by the way, after you do that merge, you'll find the eligibility tool at /benefits-eligibility instead of /public-assistance/eligibility

**Comment by trevorshannon** [comment]
Hmm, I'm not exactly sure of the problem.  I normally use `netlify dev` to start the server, but I imagine it does not really matter how the files are served, as long as the HTML and JS gets to the browser.  It is, however, a difference between our setups.


You can see if your checkbox element has the listener attached in the dev tools Elements tab:
<img width="1036" alt="Screenshot 2023-08-04 at 12 39 45 PM" src="https://github.com/theunitedeffort/theunitedeffort.org/assets/4656936/d0b256c0-8459-46eb-ba01-76b30c8d95fe">


It sounds like you are using the correct console.  Here's mine:
<img width="898" alt="Screenshot 2023-08-04 at 12 38 17 PM" src="https://github.com/theunitedeffort/theunitedeffort.org/assets/4656936/4f1f590a-f31e-4951-a617-b51bb145e92e">


Some other debugging ideas:
- Add a console log message to the `init()` function just to be sure you can see log messages.
- Add a console log message to the handler of some other element to be sure events are firing
- Use the javascript debugger to step through the code.  You can add a breakpoint in the Sources tab of Chrome dev tools or  type `debugger;` anywhere in the code to have it stop there.

**Comment by trevorshannon** [comment]
Assigning to me per a separate email discussion.
