### ISSUE TITLE
Add Homelessness Prevention System to list of supported programs

### ISSUE THREAD

**Issue by trevorshannon** [theunitedeffort/theunitedeffort.org#419]

**Comment by trevorshannon** [comment]
https://preventhomelessness.org/

**Comment by DairyProducts** [comment]
What questions should be asked for the HPS eligibility criteria?

![image](https://github.com/user-attachments/assets/c6670df9-4656-4fe0-a775-d8d57af0033d)

The requirements call for being housed but at risk of losing housing, so I don't think it is appropriate to use the "I do not have a stable place to live" selection for eligibility in this case as it may be a bit unclear.

**Comment by trevorshannon** [comment]
You are right that we should not use "no stable place" as a stand-in for risk of homelessness.  We used to have a question like this but took it out after removing the program it helped screen for.  This is what was in there before: https://github.com/theunitedeffort/theunitedeffort.org/pull/487/files#diff-57c51b14537c1c639a55767fed4cefb7dd53846895b692c98f19e4188c0dee70L298-L301

You could bring that question back and perhaps expand a bit on "at risk of losing your home" with some helpful text similar to what the HPS guidelines have.  You should be able to copy/paste a lot of code from that change removing the UPLIFT program.

**Comment by DairyProducts** [comment]
I added the HPS eligibility function:

https://github.com/theunitedeffort/theunitedeffort.org/blob/5013732a7cc894aecda74098fa09257232187b99/src/site/_includes/js/eligibility.js#L2710-L2730

However submitting the form throws this error in the browser console:

```
Uncaught TypeError: program.result is not a function
    computeEligibility http://localhost:8888/js/eligibility.js:3074
    submitForm http://localhost:8888/js/eligibility.js:1112
    addListeners http://localhost:8888/js/eligibility.js:1186
    init http://localhost:8888/js/eligibility.js:3131
    <anonymous> http://localhost:8888/benefits-eligibility/:2243
```

It seems to be that the function fails to return a valid value, but I'm not sure why. 

Also, in the future, is there an efficient way to debug these kinds of problems? I'm not very experienced here, but is there something like a "step through" debug mode showing all the variables rather than simply getting the traceback?

**Comment by trevorshannon** [comment]
Perhaps you forgot to map `program.result` to the `homelessPreventionSystemResult` function?

https://github.com/theunitedeffort/theunitedeffort.org/blob/edaca0e2879c7f4690dd39f7bcfd61f3608c421f/src/site/_includes/js/eligibility.js#L1190

Yes, browsers support javascript debugging.  In chrome, you can open the developer options (3-dot menu > More Tools > Developer Tools, or right click and choose Inspect).  Go to the Sources tab and find the js file you are interested in.  You can click to the left of a line or even within a line to set a breakpoint.  There are tons of possibilities; here is a good [primer](https://developer.chrome.com/docs/devtools/javascript).  [This page](https://javascript.info/debugging-chrome) also has a good overview.

**Comment by DairyProducts** [comment]
Thank you! I got it working.

Also, is there a way to run the lint tests locally? They always fail when I open a pull request but I don't know how to test it beforehand.

**Comment by trevorshannon** [comment]
Yes!  `npm run lint`

You can run tests too with `npm run test` (I think `npm test` also works)

Check the file package.json to see the scripts you can run.

**Comment by DairyProducts** [comment]
Thanks! I got it. I've opened the PR for this issue.
