### ISSUE TITLE
"Call for Status" could be clarified

### ISSUE THREAD

**Issue by trevorshannon** [theunitedeffort/theunitedeffort.org#57]
Especially in the filter options, which currently read:

[  ] Call for Status
[  ] Waitlist Open

I showed this site to someone, and they said "what is call for status?"

It's a good point, and this could be clarified a bit.  Maybe "Call for Availability" or "Unspecified Availability" sine the filter section heading reads "Availability"?  Not sure exactly what would be better.

**Comment by clairehubel** [comment]
Worth a discussion. Perhaps "Contact property for waitlist status" would be clearer?

**Comment by trevorshannon** [comment]
@clairehubel what do you think about "Unspecified status", "Waitlist unknown", or "Waitlist unspecified"?  I'm not in love with any of them because it feels like a bit of an admission of not knowing something.  I mean, admittedly, we do *not* know the waitlist status, but at least "Call for status" gives the person a viable next step.

We want to keep the text short, so while "Contact property for waitlist status" is indeed very clear, it will be hard to get that to fit nicely in our affordable housing filter options layout.

Hmm..."Contact property for status" is shorter.  

This is all very low priority, because what we have now works!

**Comment by trevorshannon** [comment]
I like "Call for Availability"

**Comment by clairehubel** [comment]
Yes, that would be more clear.Sent from my iPhoneOn Jun 15, 2024, at 8:00 AM, trevorshannon ***@***.***> wrote:﻿
I like "Call for Availability"

**Comment by DairyProducts** [comment]
I tried tinkering with this on another branch, and I replaced every mention of the string "Call for Status" with "Call for Availability" in the entire repository. When running the local dev server, I found that the "Call for Status" badges still read as such, and strangely the only thing that changed was the orange "warn" highlight on the badge now being absent...

Before:
![image](https://github.com/theunitedeffort/theunitedeffort.org/assets/66636627/dd1763c0-ead8-4f3a-b375-7f0ffa2ff492)
After:
![image](https://github.com/theunitedeffort/theunitedeffort.org/assets/66636627/dce18f0e-a3ea-4691-9c16-df3da632652f)

Despite the fact the phrase "Call for Status" now appears exactly zero times in the codebase:
![image](https://github.com/theunitedeffort/theunitedeffort.org/assets/66636627/0d524a18-b2f4-4c83-be60-b7cb00b926f4)

Do you know why this might be? Thanks.

**Comment by trevorshannon** [comment]
Good question.  "Call for Status" comes from Airtable.  Rental records in Airtable have a status (Waitlist Open, Call for Status, etc) and those values are used to populate the badges and the filter options. 

The code has a few places where the string "Call for Status" is hardcoded--you found all these and replaced them.  A matching change needs to be made in Airtable before the badges and filter options will work again.

Ideally we'd be able to just change the option name in Airtable and the website would handle it all (perhaps some sort of automatic enum definition or something) but for now we just have to make the change in both places.

Rather than carefully time the Airtable update to coincide with your change going live, I suggest you add a bit of code in housing.js to tweak the value of `status` to be "Call for Availability" if Airtable returns "Call for Availability" **or** "Call for Status".  That way, the website will update to "Call for Availability" and I can make the Airtable update at any time.  Once Airtable is updated, one of us can remove that backwards-compatibility patch.

**Comment by DairyProducts** [comment]
I replaced the conditional statements in the liquid files such that the badge color is now correct. I've also changed line 123 on `housing.js` such that it now uses a ternary operator:
`          openStatus: record.get('STATUS') === 'Call for Status' ? 'Call for Availability' : record.get('STATUS'),`
But the badges still display as "Call for Status". I'm not sure if this is an Airtable thing or if the badge text is collected from elsewhere.

**Comment by trevorshannon** [comment]
The API calls to Airtable are cached because Eleventy rebuilds the site every time a file is saved.  It's likely that a cached `housingList` object was being used, so it still had the "Call for Status" values within.  You can either temporarily make the cache [expire very quickly](https://github.com/theunitedeffort/theunitedeffort.org/blob/64b30671fa5caa1fbed5a4eb608dd950181e02f5/src/site/_data/housing.js#L239) (I like to use `'1s'` if I'm developing with an Airtable dependency) or delete the contents of the `.cache` folder (it will be hidden on some systems).

The Eleventy output will [say](https://github.com/theunitedeffort/theunitedeffort.org/blob/64b30671fa5caa1fbed5a4eb608dd950181e02f5/src/site/_data/housing.js#L246) whether the site is using cached data or fetching data from Airtable.

Hopefully that fixes it.

**Comment by DairyProducts** [comment]
It appears that this is the solution- I didn't need to change the cache duration because I shut down my local dev server previously and then restarted it more than an hour later.
