### ISSUE TITLE
Update "Call for Status" in Airtable

### ISSUE THREAD

**Issue by DairyProducts** [theunitedeffort/theunitedeffort.org#613]
**See #57 and #611.**

Airtable currently returns a value of "Call for Status" for one of the status badges. As a fix for the above issue, the website's status badge will now display "Call for Availability". On Airtable, however, the status value is still "Call for Status" as it is difficult to change the Airtable value without immediately publishing site changes. The current fix is backward compatible; the status badge on the website will always read "Call for Availability" regardless of whether it's "Call for Status" or "Call for Availability" on Airtable. 

When the change is made on Airtable, the changes made in `housing.js` on #611 should be more or less reverted as it will no longer be needed.

**Comment by DairyProducts** [comment]
Duplicate of #612.

**Comment by trevorshannon** [comment]
Ah thanks for that!  sorry our issues crossed
