### ISSUE TITLE
Design Eligibility Screening Tool 

### ISSUE THREAD

**Issue by clairehubel** [theunitedeffort/theunitedeffort.org#98]
@trevorshannon  

We are working on developing an eligibility screening tool that can screen clients and determine which benefits they may be eligible for. Wei and I have different visions on how to achieve this, so she is working on it within our CRM, (Apricot) and I would like to work on this for the website.

The idea is that we could develop a screening tool that can be shared by other agencies to generate a comprehensive list of all services/benefits for which clients are eligible, making a service plan in the process. Ideally the related application forms could be printed at the end of this process, in order to make a smooth, efficient, and customized plan. 

If we can make a list of the benefits we are focusing on, and the eligibility criteria for each, it would be awesome if you could help me generate code with conditional logic to work through this.

I could envision having this as a main tab on the home screen, right after Housing. I think other agencies would love to have access to this. I have seen many versions, but they tend to be very clunky and complicated.

This is a substantial project, so we should discuss where it falls in our priority list, and whether you are up for having a god at it!

:)

**Comment by trevorshannon** [comment]
Cool, yes let's discuss on a call and see what makes sense.

**Comment by philhawksworth** [comment]
I gather that the qualification criteria for the various benefits might be quite broad and sometimes interdependent.
Being able to capture, describe, and visualise these rules will be an important first step towards this goal.

Do you think it might be possible to work on a matrix of these criteria and benefits in something like a shared google sheet so that the rules could start being discussed and explored, @clairehubel?

**Comment by clairehubel** [comment]
Yes, absolutely. This is in progress/mostly done, and is definitely the place to start. I'll work on that part and a few notes. I won't be able to do much this week bc of traveling for Mae's graduation (yay!), but I think there are a few things that @trevorshannon can work on in the meantime. Taking a break for a few days is also fine :)

**Comment by philhawksworth** [comment]
Great!

This one feels large enough to me that we should plan it as its own milestone. That way we can collect issues into that milestone which we progress appropriately, meanwhile we have another milestone with no close date which collects all the ad hoc iterations and improvements we want to work on which are not specific to delivering the eligibility screening tool.

It will help us keep moving things forward steadily without getting blocked by the larger effort needed for this feature.

Sound ok to you @trevorshannon and @clairehubel ?

**Comment by clairehubel** [comment]
Good idea to have this as the next major milestone. It's a pretty meaty coding project, I think. It is also going to be a significant gift to our partner organizations, once we get it running, so it's appropriate to think of it as a big milestone.

I think @trevorshannon and I may need to have a strategy session after I get back, to plan out our upcoming projects. Some of them are likely reasonably quick fixes, whereas others are more involved. 

I think I need to do some homework for this before we can decide how long it will take. I will provide this asap, but maybe after this week since things are quite busy on the home front.

**Comment by trevorshannon** [comment]
Yes I agree this will be a large project.  No issue waiting a bit before strategizing.  I have the db training and some little remaining website issues to keep me busy.

**Comment by trevorshannon** [comment]
@rajivrajiv and I will begin work on this soon.  Currently I am organizing all the eligibility requirements in to a [spreadsheet](https://docs.google.com/spreadsheets/d/1chqXgs4_g5pqz52ZwQ9P9VFiHTw8bSOVzfPlTkcfvks/edit#gid=248547039) that will inform our eventual HTML/Javascript form logic.

**Comment by trevorshannon** [comment]
Here is a [mockup](https://docs.google.com/presentation/d/1GZGhu7K2GtutdVy3EugUAZfc80Clt7id7b8CJo7YMBg/edit#slide=id.p) of the eventual web form

**Comment by trevorshannon** [comment]
This tool is now released to beta testers.  Closing this umbrella issue in favor of future issues that will track individual bugs or feature requests for the eligibility tool.
